<?php /** @var \JustBetter\Sentry\Block\SentryScript $block */ ?>


<?php if ($block->useLogRocketIdentify()): ?>

    define('customerData',
        ['jquery', 'Magento_Customer/js/customer-data'],
        function ($, customerData) {
            'use strict';

            var getCustomerInfo = function () {
                var customer = customerData.get('customer');

                return customer();
            };

            var isLoggedIn = function (customerInfo) {
                return customerInfo && customerInfo.firstname;
            };

            return function () {
                var deferred = $.Deferred();
                var customerInfo = getCustomerInfo();

                if (customerInfo && customerInfo.data_id) {
                    deferred.resolve(isLoggedIn(customerInfo), customerInfo);
                } else {
                    customerData.reload(['customer'], false)
                        .done(function () {
                            customerInfo = getCustomerInfo()
                            deferred.resolve(isLoggedIn(customerInfo), customerInfo);
                        })
                        .fail(function () {
                            deferred.reject();
                        });
                }

                return deferred;
            };

        }
    );

    require(["customerData"], function (customerData) {

        customerData().then(function (loggedIn, data) {
            if (!loggedIn) {
                return;
            }

            LogRocket.identify(data.websiteId, {
                name: data.fullname,
                email: data.email
            });

        });
    });


<?php endif; ?>
