<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/** @var \JustBetter\Sentry\Block\SentryScript $block */

if (!$block->canUseScriptTag($block->getNameInLayout())) {
    return;
}
?>

<script src="https://browser.sentry-cdn.com/<?= \JustBetter\Sentry\Block\SentryScript::CURRENT_VERSION;?>/bundle.min.js"
        crossorigin="anonymous">
</script>
<script>
    Sentry.init({
        dsn: '<?= $block->escapeUrl(trim($block->getDSN())); ?>',
        release: '<?= $block->escapeHtml(trim($block->getVersion())); ?>'
    });
</script>
