<?php
/**
 * @var \JustBetter\Sentry\Block\Adminhtml\System\Config\Button $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="actions actions-test-sentry">
    <button class="actions-test-sentry" 
            type="button" 
            id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#<?= $block->getHtmlId() ?>": {
            "validation": {},
            "justbetter/testsentry": {
                "ajaxUrl": "<?= /* @noEscape */ $block->getButtonUrl() ?>"
            }
        }
    }
</script>
