<?php
/** @var \JustBetter\Sentry\Block\Adminhtml\System\Config\Button $block */
?>
<div class="actions actions-test-sentry">
    <button class="actions-test-sentry" 
            type="button" 
            id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#<?= $block->getHtmlId() ?>": {
            "validation": {},
            "justbetter/testsentry": {
                "ajaxUrl": "<?= /* @noEscape */ $block->getButtonUrl() ?>"
            }
        }
    }
</script>
