<?php
  /**
   * @var \JustBetter\Sentry\Block\Adminhtml\System\Config $block
   * @var \Magento\Framework\Escaper $escaper
   */
?>
<td></td>
<td>
    <h2><?= $escaper->escapeHtml(__('How to configure Sentry?')); ?></h2>
    <p><?= $escaper->escapeHtml(__('This module uses the')); ?>
        <a href="https://devdocs.magento.com/guides/v2.3/config-guide/config/config-php.html" target="_BLANK">
            <?= $escaper->escapeHtml(__('Magento Deployment Configuration')); ?>
        </a>
        <?= $escaper->escapeHtml(__('for most it\'s configuration. This means that you need to add this array to your `app/etc/env.php`:')); ?>
    </p>

    <pre>
<?= /* @noEscape */ htmlentities("
'sentry' => [
    'dsn' => 'example.com',
    'logrocket_key' => 'example/example',
    'environment' => null,
    'log_level' => \Monolog\Logger::WARNING,
    'error_types' => E_ALL,
    'ignore_exceptions' => [],
    'mage_mode_development' => false,
]"); ?>
    </pre>

    <p><?= $escaper->escapeHtml(__("Release ID: %1", $block->getVersion())); ?></p>
</td>
