<td></td>
<td>
    <h2><?= $block->escapeHtml(__('How to configure Sentry?')); ?></h2>
    <p><?= $block->escapeHtml(__('This module uses the')); ?>
        <a href="https://devdocs.magento.com/guides/v2.3/config-guide/config/config-php.html" target="_BLANK">
            <?= $block->escapeHtml(__('Magento Deployment Configuration')); ?>
        </a>
        <?= $block->escapeHtml(__('for most it\'s configuration. This means that you need to add this array to your `app/etc/env.php`:')); ?>
    </p>

    <pre>
<?= /* @noEscape */ htmlentities("
'sentry' => [
    'dsn' => 'example.com',
    'logrocket_key' => 'example/example',
    'environment' => null,
    'log_level' => \Monolog\Logger::WARNING,
    'mage_mode_development' => false,
]"); ?>
    </pre>

    <p><?= $block->escapeHtml(__("Release ID: %1", $block->getVersion())); ?></p>
</td>
